### ISSUE TITLE
Editing

### ISSUE THREAD

**Issue by davidroyer** [getflywheel/local-addon-notes#1]
Hello,

Just installed this Add-On and it's brilliant and I love it.
One question though...Is it not possible to edit a note once you add it?

Thanks!

**Comment by jhonkaman** [comment]
I'm also wondering this. If it isn't currently possible, I think this would be a great feature to add!

**Comment by josh-collinsworth** [comment]
+1 for editing

**Comment by greenphp** [comment]
+1 for editing too. :)

**Comment by alexclst** [comment]
+1 for editing support.

**Comment by mostafaabobakr7** [comment]
+1 for editing support too :)

**Comment by fabriziofeitosa** [comment]
+1 for editing

**Comment by haseeb-dc** [comment]
+1 for editing

**Comment by mircobabini** [comment]
+1 for editing

**Comment by mircobabini** [comment]
**UPDATE:** I did it.  #16

I love Mocaccino btw!

[!["Buy Me A Coffee"](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png)](https://paypal.me/mircobabini/10)

**Comment by tresorama** [comment]
I added this feature yesterday on a fork, and opened a PR #29
If it will be merged the feature will be soon publicly available.

**Comment by carterlando** [comment]
+1 I really need this feature implemented
